### ISSUE TITLE
Kanban Board erstellen

### ISSUE THREAD

**Issue by skidrowski** [PG-MATE/Organisation#12]

**Comment by SebastianSchmidt** [comment]
Spalten, die @skidrowski und ich uns überlegt haben:

- Backlog
- Wird spezifiziert
- Spezifiziert
- In Umsetzung
- Umgesetzt
- Im Test
- Getestet

**Comment by PMudra** [comment]
Kann das Board am Dienstag vorgestellt werden und über den Einsatz diskutiert werden?

**Comment by skidrowski** [comment]
Ja.
