### ISSUE TITLE
S-100 evaluieren

### ISSUE THREAD

**Issue by skidrowski** [PG-MATE/Organisation#13]
http://www.emaritime.de/

**Comment by icebreaker2** [comment]
In MTSS (Maritime Transportation Systems Simulation) und laut Arne bietet eMIR eine vollständige Implementierung von S-100 über entsprechende Java-Bibliotheken.

**Comment by SebastianSchmidt** [comment]
Ist die Implementierung frei erhältlich? Vielleicht als Maven-Artifact?

**Comment by icebreaker2** [comment]
Wird nachgefragt. Ansosnten schau ich selbst nochmala auf deren Seite.

**Comment by icebreaker2** [comment]
Als Plugin einbindbar:

http://ems.informatik.uni-oldenburg.de:3195/nexus/content/unzip/eMirUpdateSite/de/emir/eMIR.UpdateSite/0.0.1-SNAPSHOT/eMIR.UpdateSite-0.0.1-SNAPSHOT.zip-unzip/

Werde ich ausprobieren!

**Comment by skidrowski** [comment]
Wird geschlossen, da das Ticket kein klares Ziel hat. Weitere Themen in neuen Tickets zusammenfassen und Ziel benennen.
