### ISSUE TITLE
EPD-Workshop planen und durchführen

### ISSUE THREAD

**Issue by stromhalm** [PG-MATE/Organisation#14]

**Comment by PMudra** [comment]
Ist meiner Meinung nach erstmal nicht mehr nötig. Am 8.12 werden die Ergebnisse der einzelnen Gruppen vorgestellt. Falls dann eine EPD Workshop nötig wird, kann man den Task wieder öffnen.

@stromhalm bitte schließen, falls du derselben meinung bist.

**Comment by stromhalm** [comment]
Stimme @PMudra zu.
