### ISSUE TITLE
Einen Termin für ein "Soziales Event" finden / vorbereiten

### ISSUE THREAD

**Issue by stromhalm** [PG-MATE/Organisation#15]

**Comment by PMudra** [comment]
Ein paar Ideen:
* Escape room
* Laser Tag
* Kneipe
* Ruhiger Abend bei jemandem Zuhause

**Comment by SebastianSchmidt** [comment]
Einen ruhigen Abend könnte man mit einem Spieleabend verbinden. Den wahren Charakter eines Menschen sieht man immer dann, wenn er/sie gewinnt oder verliert! :D

**Comment by PMudra** [comment]
Infos sind in Telegram zu finden.
