### ISSUE TITLE
Workshop zum Test-driven development vorbereiten

### ISSUE THREAD

**Issue by SebastianSchmidt** [PG-MATE/Organisation#17]
- [x] Repository vorbereiten.
- [x] Präsentation vorbereiten.
- [x] Praktische Aufgabe vorbereiten.

**Comment by PMudra** [comment]
Model-Driven könnte ja eventuell auch noch interessant sein, je nachdem für was wir uns bei den einzelnen Komponenten entscheiden.

**Comment by SebastianSchmidt** [comment]
@PMudra Genau, einen solchen Workshop könnten wir dann ja "On-Demand" machen.

**Comment by SebastianSchmidt** [comment]
Repository als Grundlage für den Workshop erstellt: https://github.com/SebastianSchmidt/Test-Driven-Development-QuickStart

**Comment by SebastianSchmidt** [comment]
Präsentation und praktische Aufgabe vorbereitet.
