### ISSUE TITLE
WLAN-Zugang im OFFIS

### ISSUE THREAD

**Issue by SebastianSchmidt** [PG-MATE/Organisation#20]
Für unseren Termin am 08.11.2016 benötigen wir einen WLAN-Zugang im OFFIS.

**Comment by Beriko** [comment]
Auf meine Frage per Mail "Wie siehts denn überhaupt mit WLAN dort aus? Ist zumindest Offis-Guests erreichbar?" kam keine Antwort von Arne, andere Sachen aus der gleichen Mail wurden beantwortet. @icebreaker2  guckt morgen nach, wenn er den Schlüssel holt.

**Comment by icebreaker2** [comment]
Über OFFIS Guest erreichbar. Passwort wird von mir vergeben.
