### ISSUE TITLE
Folien der Präsentation hochladen

### ISSUE THREAD

**Issue by PMudra** [PG-MATE/Organisation#22]
- [x] Luca Gatterdam
- [x] Adrian Jagusch
- [x] Hendrik Kahlen
- [x] Sergej Kidrowski
- [x] Thorben Kloppe
- [x] Berislaw Kock
- [x] Philipp Mudra
- [x] Mark Otten
- [x] Merle Paul
- [x] Sebastian Schmidt
- [x] Maximilian Wappler
- [x] Tim Wiechmann

**Comment by PMudra** [comment]
@skidrowski bitte abschließen

**Comment by skidrowski** [comment]
Präsentation hochgeladen. Da nun alle vorliegen, schließe ich das Ticket.
