### ISSUE TITLE
Schnittstellen und Datenkapselung definieren

### ISSUE THREAD

**Issue by icebreaker2** [PG-MATE/Organisation#24]
Grafische Darstellung unseres Gesamtaufbaus der Plattform

**Comment by icebreaker2** [comment]
Bilddatei angehangen. Ist nicht final, aber erstmal etwas über das wir dann noch reden können.

**Comment by PMudra** [comment]
Ich denke dieser Task kann dicht, da jetzt die Teams einzeln Infos dazu sammeln?

**Comment by icebreaker2** [comment]
Ist richtig.
