### ISSUE TITLE
Echte Namen bei Github eintragen

### ISSUE THREAD

**Issue by PMudra** [PG-MATE/Organisation#32]
Bitte die echten Namen im Github Profil eintragen. Das hilft beim Heraussuchen der Assignees in Tasks.
Der Vorname reicht auch schon denke ich. Bei Merle ist es ja auch so schon klar, aber zur Vollständigkeit würde ich es auch da einfach machen :smiley: 

- [x] @MerlePaul 
- [x] @FRiGiDiTy

**Comment by FRiGiDiTy** [comment]
Erledigt :)

**Comment by MerlePaul** [comment]
Erledigt
