### ISSUE TITLE
Organisation in Wiki übertragen

### ISSUE THREAD

**Issue by skidrowski** [PG-MATE/Organisation#6]

**Comment by skidrowski** [comment]
@SebastianSchmidt: Bitte Wiki im Organisationsrepository einfügen.

**Comment by maximilianwappler** [comment]
@SebastianSchmidt: Teile mir bitte mit, wenn du #7 abgeschlossen hast, da ich diesen Task vorher nicht lösen kann

**Comment by PMudra** [comment]
Kann hier nochmal jemand erklären, was damit gemeint war?

**Comment by maximilianwappler** [comment]
Wir wollten die Organisation, also Protokolle etc. Ins Wiki oder was auch immer übertragen, wenn wir uns für eine Alternative entschieden haben

**Comment by stromhalm** [comment]
Aufgrund der Beschränkungen des GitHub-Wikis (u.a. keine Pull Requests und Dateihierarchie im Webinterface möglich) wurde entschieden für die Organisation weiterhin dieses Repository zu  verwenden.
