### ISSUE TITLE
Gitbook evaluieren

### ISSUE THREAD

**Issue by skidrowski** [PG-MATE/Organisation#7]

**Comment by SebastianSchmidt** [comment]
- GitBooks können über eine Weboberfläche oder über eine [Desktop-Anwendung](https://www.gitbook.com/editor) bearbeitet werden.
- GitBook kann [mit GitHub integriert](https://help.gitbook.com/github/can-i-host-on-github.html) werden.
   - Änderungen über GitBook werden direkt in einem GitHub-Repository durchgeführt.
   - Änderungen in dem GitHub-Repository lösen automatisch eine Aktualisierung von PDFs oder Webseiten durch GitBook aus.

**Comment by SebastianSchmidt** [comment]
- GitBook ist für Einzelpersonen und öffentliche Bücher [kostenlos](https://www.gitbook.com/pricing).
- GitBook ist für Organisationen [kostenpflichtig](https://www.gitbook.com/pricing).
- Für Open Source Projekte scheint es eine Möglichkeit zu geben, GitBook kostenlos zu nutzen: "Open source project? We'd love to host you for free!". Dafür muss GitBook [kontaktiert](https://www.gitbook.com/contact) werden.

**Comment by SebastianSchmidt** [comment]
Ergebnis für das Treffen am 08.11.2016 zusammengefasst.
