### ISSUE TITLE
Zutritt für Offis Raum am 08.11.2016 verschaffen

### ISSUE THREAD

**Issue by skidrowski** [PG-MATE/Organisation#8]

**Comment by Beriko** [comment]
.

**Comment by Beriko** [comment]
Zitat Arne zu Hendrik: "Unsere Technische Verwaltung sagt er kann sich einfach den Schlüssel abholen, da er den Pfand und die Unterlagen erledigt hat. "
Arne selber ist nur bis ca. 17:00 Uhr da und würde uns dann rausschmeißen.

**Comment by icebreaker2** [comment]
Ich habe einen Schlüssel erhalten. Raum steht zur Verfügung. Bis die anderen Schlüsselträger haben, werde ich immer da sein.
